# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: dott. Francesco Ciaghi - Fisioterapista sportivo, Certified Mulligan Practitioner
email: ft.francescociaghi@gmail.com
phone: 346/3969863 
address: Corso Rosmini 53/2, Rovereto (TN)
description: >- # this means to ignore newlines until "baseurl:"
  Nel 2016 ho conseguito la laurea in Fisioterapia presso la sede di Rovereto dell'Università degli Studi di Verona.
  Attratto dall’ambito sportivo ho iniziato nel 2019 il Master di Fisioterapia Applicata allo Sport dell’Università di Siena. 
  Libero professionista, in studio e presso le squadre che sto seguendo, di football americano e di calcio, mi occupo di problematiche sportive e non solo.
# baseurl: "/francescociaghi.me" # the subpath of your site, e.g. /blog
url: "https://aaronsama.github.io"
# url: https://francescociaghi.me # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - octopress-debugger
  # - jekyll-paginate

# paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# theming and stuff

show_excerpts: true
minima:
  social_links:
    instagram: fciaghi.fisio
    facebook: fciaghifisio
    whatsapp: "+393463969863"

sass:
  sass_dir: assets/css
